version: '3.3'

networks:
  inventare:
    driver: bridge

services:
  database:
    image: mysql:5.6
    volumes:
      - ./database:/var/lib/mysql
    networks: 
      - inventare
    environment:
      MYSQL_ROOT_PASSWORD: root

  api:
    depends_on:
      - database
    build: ./packages/core/api
    volumes:
      - ./packages/core/api/src:/app/src
      - ./packages/core/api/nodemon.json:/app/nodemon.json
      - ./packages/core/api/tsconfig.json:/app/tsconfig.json
    ports:
      - "3333:3333"
    networks: 
      - inventare
    environment:
      SQL_HOST: database
      SQL_USER: root
      SQL_PASSWORD: root
    command: npm run dev
