FROM node:14-alpine

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY packages/core/admin ./packages/core/admin

RUN yarn install --pure-lockfile --non-interactive

WORKDIR /app/packages/core/admin

RUN yarn build
