version: '3.3'

networks:
  inventare:
    driver: bridge

services:
  database:
    image: mysql:5.6
    volumes:
      - ./database:/var/lib/mysql
    networks: 
      - inventare
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventare

  api:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./packages/core/api/src:/app/packages/core/api/src
      - ./packages/core/api/nodemon.json:/app/packages/core/api/nodemon.json
      - ./packages/core/api/tsconfig.json:/app/packages/core/api/tsconfig.json
    ports:
      - "3333:3333"
    networks: 
      - inventare
    environment:
      SQL_HOST: database
      SQL_USER: root
      SQL_PASSWORD: root
    command: yarn dev
  
  admin:
    depends_on: 
      - database
      - api
    build:
      context: .
      dockerfile: Dockerfile.admin
    volumes:
      - ./packages/core/admin/public:/app/packages/core/admin/public
      - ./packages/core/admin/src:/app/packages/core/admin/src
      - ./packages/core/admin/.env:/app/packages/core/admin/.env
      - ./packages/core/admin/tsconfig.json:/app/packages/core/admin/tsconfig.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: yarn start
