FROM node:14-alpine

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ADD ./package.json /app/package.json
ADD ./packages/core/admin/package.json /app/packages/core/admin/package.json
ADD ./yarn.lock /app/yarn.lock
RUN yarn install
ADD ./packages/core/admin /app/packages/core/admin
