version: "3"

services:
  elasticsearch_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch_test
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    
  database_test:
    image: mariadb
    container_name: database_test
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: inventare
      MYSQL_ROOT_PASSWORD: root
