# Generated by Django 3.2.5 on 2021-08-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_rendered',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
