# Generated by Django 3.2.5 on 2021-08-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_question_text_rendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionalternative',
            name='text_rendered',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionresolution',
            name='text_rendered',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresolution',
            name='text',
            field=models.TextField(blank=True, default='', help_text='Escreva o texto da resolução.', verbose_name='Texto da Resolução'),
        ),
    ]
